### ISSUE TITLE
参考书目.md的线代部分建议加上国外教材，工大教材害人不浅

### ISSUE THREAD

**Issue by Kethers** [hewei2001/HITSZ-CS-GEEK#12]
比如David C Lay的 线性代数及其应用（有中译本），或者Gilbert strang的Intruduction to Linear Algebra（English only，国内清华大学有出版黄皮的线性代数，目前是THU线代教材，当当有售，不过依旧是英文，所以建议直接找电子版的）。
至于电子版教材建议联系实验中心的老师看能不能搭个内网的文件传输配合着来弄（

**Comment by hewei2001** [comment]
[参考书目.md]里暂时放的都是我校上课用的教材  🔮 ，是方便大家想买书时找到对应的作者版本的。如果要推荐教材，欢迎在/线性代数/readme.md文件里加 💯 ，感谢~

**Comment by hewei2001** [comment]
后续会考虑建立校园内网的文件传输渠道滴

**Comment by Kethers** [comment]
I am currently working on writing the readme.md under Linear Algebra file-folder. Later I wil pull a request, plz check.

**Comment by hewei2001** [comment]
> 
> 
> I am currently working on writing the readme.md under Linear Algebra file-folder. Later I wil pull a request, plz check.

Checked already, thanks a lot. I have added your name to the contributors. 👍
