### ISSUE TITLE
仓库内容增添建议

### ISSUE THREAD

**Issue by CandyOre** [hewei2001/HITSZ-CS-GEEK#14]
两个建议
1. 对某些课程的理解性的文章，大概是，给大家参考，可以添加分类“学科杂谈”之类的目录。我是大一的小透明，暂时只准备写线性代数（个人成绩期末49总分96）和数据结构；
2. 一些非培养方案内课程的理解性的文章，大概是，立足于cs，学习其他学科的攻略？包括cs内不开课的学科，其他理科学科，其他人文学科。

**Comment by hewei2001** [comment]
Re:
1. “理解性文章”或许跟课程攻略有点类似，是否可以写到对应课程目录下的readme.md里呢？（可能模板中没有该块，可以在后面补上），或者，如果你愿意分享更多，可以在对应课程下的/note/目录中新建一个/2020_name/xxx.md，来放上你的想法，这样可以让更多对这个课程感兴趣的同学直接找到你的文章！ 👍 
2. 非方案内的课程我也设想过，如一些国外学校开设的名课，如Andrew-Ng的ML课等，等有人愿意上传相关的笔记再新建一个文件夹存放叭 😄 到时候其他理科、人文课程也可以放进去。

**Comment by CandyOre** [comment]
Re:
1. 放到readme可能不太合适，因为对学科的理解每个人可能不太一样，主观性比较强，可能比较容易出错(*^▽^*)。（而且可能过几年自己看都会觉得理解得有些幼稚了owo..），感觉在note里添加是个好办法，也希望看到更多小伙伴的个人理解~（今天下午就pr上233）
2. 好耶~个人目前在看计算机图形学基础，看完后应该会大概写篇文章捋一捋（没有笔记qwq）。

**Comment by hewei2001** [comment]
感谢贡献！！如果没有别的事情就关闭这个issue啦，稍后将你列入贡献者名单。

**Comment by Kethers** [comment]
> Re:
> 
> 1. 放到readme可能不太合适，因为对学科的理解每个人可能不太一样，主观性比较强，可能比较容易出错(_^▽^_)。（而且可能过几年自己看都会觉得理解得有些幼稚了owo..），感觉在note里添加是个好办法，也希望看到更多小伙伴的个人理解~（今天下午就pr上233）
> 2. 好耶~个人目前在看计算机图形学基础，看完后应该会大概写篇文章捋一捋（没有笔记qwq）。

学弟从哪看计算机图形学啊？我大三从寒假开始看的，可以交流一下，个人觉得吃透GAMES101就很猛了

**Comment by CandyOre** [comment]
> > Re:
> > 
> > 1. 放到readme可能不太合适，因为对学科的理解每个人可能不太一样，主观性比较强，可能比较容易出错(_^▽^_)。（而且可能过几年自己看都会觉得理解得有些幼稚了owo..），感觉在note里添加是个好办法，也希望看到更多小伙伴的个人理解~（今天下午就pr上233）
> > 2. 好耶~个人目前在看计算机图形学基础，看完后应该会大概写篇文章捋一捋（没有笔记qwq）。
> 
> 学弟从哪看计算机图形学啊？我大三从寒假开始看的，可以交流一下，个人觉得吃透GAMES101就很猛了

学长大佬好~

老GAMES101了hhh，我刚入门啦，看完transformation和rasterization，目前感觉还不怎么难，可能得做点题目验证下自己的理解（虎书qwq）。感觉GAMES101课程整体连贯性、逻辑性比较强，可能自己会有些感受，所以感觉学完后可能能写出一篇理解性文章，给咱仓库开个头。

感觉图形学可以有个前置课程“计算几何”，参考学堂在线邓俊辉老师的课（邓公yyds awa）；后续可能考虑GAMES其他课程和科大的《数字几何处理》。可以加个QQ以后交流，834657460

**Comment by hewei2001** [comment]
居然讨论起了学术话题(ﾉ*･ω･)ﾉ好的，这才像是这个仓库issue该有的样子hhhh
