### ISSUE TITLE
建议增加gitee镜像

### ISSUE THREAD

**Issue by W-Hsu** [hewei2001/HITSZ-CS-GEEK#16]
由于github访问速度有时抽风，为了没有梯子的同学，可以考虑一下开通gitee镜像。

**Comment by hewei2001** [comment]
好的，感谢你的提议。我已在gitee创建同名仓库并同步过去，但是gitee的镜像好像不会一起更新，可能会存在一些滞后，如果想要用gitee可以先fork本仓库，然后再登录自己的gitee账号，同步自己的仓库过去，保证是最新的内容。
