### ISSUE TITLE
readme 最后协议的文本与链接不匹配

### ISSUE THREAD

**Issue by C6H5-NO2** [hewei2001/HITSZ-CS-GEEK#25]
链接是 BY-NC-SA，而文本是 BY-SA。如果本仓库的协议是 BY-SA 的话，理论上可能不能引用浙大仓库的前言。

**Comment by hewei2001** [comment]
> 
> 
> 链接是 BY-NC-SA，而文本是 BY-SA。如果本仓库的协议是 BY-SA 的话，理论上可能不能引用浙大仓库的前言。

好的，感谢您，之前建仓库时没有注意到这点（好像清华的仓库也错了），已经修改过来了，应该是BY-NC-SA。

此外，浙大仓库中也有此协议，应该算是相同方式共享了，并且本仓库引用其前言时也加了署名。

本人对这方面没有研究过，如果有说错的欢迎指正，欢迎提出修改意见！

**Comment by C6H5-NO2** [comment]
根据官网 [Compatible Licenses](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses)

> Your contributions to adaptations of material under BY-NC-SA 4.0 may only be licensed under:
>
> - BY-NC-SA 4.0, or a later version of the BY-NC-SA license.
> - Ported versions of the BY-NC-SA license, version 4.0 or later.
> - A license designated as a “BY-NC-SA Compatible License” as defined in BY-NC-SA 4.0.

BY-SA 不与 BY-NC-SA 兼容。不过 readme 已经改成 BY-NC-SA 的话，那就没事了。
